web:
  build: .
  command: "runserver 0.0.0.0:8000"
  environment:
      PYTHONUNBUFFERED: 0
      DJANGO_SETTINGS_MODULE: sack.settings.base
  entrypoint:
   - './manage.py'
  links:
   - db
  volumes:
   - .:/opt/code
  ports:
   - "8010:8000"
data:
  image: aexea/aexea-base
  volumes:
    - /home/uid1000
db:
  image: postgres:10
